"""Encoder, adapter, typed-head, and artifact-export components."""

from semantscript_model.calibration import (
    DEFAULT_ECE_BIN_COUNT,
    DEFAULT_MAXIMUM_TEMPERATURE,
    DEFAULT_MINIMUM_TEMPERATURE,
    DEFAULT_TEMPERATURE_ITERATIONS,
    MAXIMUM_ECE_BIN_COUNT,
    MAXIMUM_TEMPERATURE,
    MAXIMUM_TEMPERATURE_ITERATIONS,
    MINIMUM_TEMPERATURE,
    CalibrationMetrics,
    CalibrationResult,
    calibrate,
    calibration_metrics,
    fit_temperature,
    temperature_scaled_probabilities,
)
from semantscript_model.classifier import SemanticClassifier
from semantscript_model.encoder import (
    DEFAULT_ENCODER,
    DEFAULT_ENCODER_REVISION,
    EncoderConfig,
    SentenceEncoder,
)
from semantscript_model.export import (
    DEFAULT_MAXIMUM_COMPONENT_BYTES,
    DEFAULT_PARITY_ABSOLUTE_TOLERANCE,
    DEFAULT_PARITY_RELATIVE_TOLERANCE,
    MAXIMUM_PARITY_ABSOLUTE_TOLERANCE,
    MAXIMUM_PARITY_RELATIVE_TOLERANCE,
    MAXIMUM_PARITY_SEQUENCE_LENGTH,
    ONNX_OPSET,
    ExportedOnnxComponent,
    ExportedOnnxComponents,
    TensorMetadata,
    export_onnx_components,
)
from semantscript_model.heads import (
    ClassificationHead,
    HeadArchitecture,
    HeadConfig,
    HeadKind,
)
from semantscript_model.losses import (
    RPS_WEIGHT,
    SPHERICAL_WEIGHT,
    LossName,
    Reduction,
    classification_loss,
    proper_scoring_loss,
)

PACKAGE_NAME = "semantscript_model"

__all__ = [
    "DEFAULT_ECE_BIN_COUNT",
    "DEFAULT_ENCODER",
    "DEFAULT_ENCODER_REVISION",
    "DEFAULT_MAXIMUM_COMPONENT_BYTES",
    "DEFAULT_MAXIMUM_TEMPERATURE",
    "DEFAULT_MINIMUM_TEMPERATURE",
    "DEFAULT_PARITY_ABSOLUTE_TOLERANCE",
    "DEFAULT_PARITY_RELATIVE_TOLERANCE",
    "DEFAULT_TEMPERATURE_ITERATIONS",
    "MAXIMUM_ECE_BIN_COUNT",
    "MAXIMUM_PARITY_ABSOLUTE_TOLERANCE",
    "MAXIMUM_PARITY_RELATIVE_TOLERANCE",
    "MAXIMUM_PARITY_SEQUENCE_LENGTH",
    "MAXIMUM_TEMPERATURE",
    "MAXIMUM_TEMPERATURE_ITERATIONS",
    "MINIMUM_TEMPERATURE",
    "ONNX_OPSET",
    "PACKAGE_NAME",
    "RPS_WEIGHT",
    "SPHERICAL_WEIGHT",
    "CalibrationMetrics",
    "CalibrationResult",
    "ClassificationHead",
    "EncoderConfig",
    "ExportedOnnxComponent",
    "ExportedOnnxComponents",
    "HeadArchitecture",
    "HeadConfig",
    "HeadKind",
    "LossName",
    "Reduction",
    "SemanticClassifier",
    "SentenceEncoder",
    "TensorMetadata",
    "calibrate",
    "calibration_metrics",
    "classification_loss",
    "export_onnx_components",
    "fit_temperature",
    "proper_scoring_loss",
    "temperature_scaled_probabilities",
]
