"""Generated by scripts/generate-remedies.mjs from diagnostics/remedies.json; do not edit."""

REMEDY_TEMPLATES_JSON = r"""{
 "gold-rule-constraint": {
  "family": "verifier",
  "fix": "add the constraint always(() => {predicate}, {output}): the {count} missed examples all have {predicate} and expect {output}, and every teacher-labelled case where it holds agrees",
  "params": [
   "predicate",
   "output",
   "count"
  ]
 },
 "gold-repeated-miss-example": {
  "family": "verifier",
  "fix": "add the examples entry {example}: {count} teacher-labelled case(s) that expect {expected} are also predicted {predicted}",
  "params": [
   "example",
   "count",
   "expected",
   "predicted"
  ]
 },
 "gold-check-example": {
  "family": "verifier",
  "fix": "check the example {case} against the teacher's labels (it expects {expected}, the model predicts {predicted}): if it is right, add examples near it or a constraint for its rule; if not, correct it",
  "params": [
   "case",
   "expected",
   "predicted"
  ]
 },
 "violation-example": {
  "family": "verifier",
  "fix": "add the examples entry {example}: constraint {index} ({source}) is broken by {count} records",
  "params": [
   "example",
   "index",
   "source",
   "count"
  ]
 },
 "violation-denser-data": {
  "family": "verifier",
  "fix": "sample the boundaries more densely: rerun with --cases {cases} (now {current}) or a higher --counterfactual-ratio, or record a tolerance with --max-constraint-violation-rate (decision-8)",
  "params": [
   "cases",
   "current"
  ]
 },
 "calibration-more-cases": {
  "family": "verifier",
  "fix": "rerun with --cases {cases} (now {current}): ECE {ece} is measured on {rows} calibration rows, and more cases give more of them",
  "params": [
   "cases",
   "current",
   "ece",
   "rows"
  ]
 },
 "calibration-more-epochs": {
  "family": "verifier",
  "fix": "rerun with --epochs {epochs} (now {current}): accuracy {accuracy} shows an underfit head, which calibrates poorly",
  "params": [
   "epochs",
   "current",
   "accuracy"
  ]
 },
 "seed-retry-attempts": {
  "family": "verifier",
  "fix": "rerun with --seed-attempts {attempts}: the failure was narrow, and the retry trains the next seeds on the cached datasets without a teacher request",
  "params": [
   "attempts"
  ]
 },
 "seed-retry-next-seed": {
  "family": "verifier",
  "fix": "rerun with --seed {seed}: seeds {first} to {last} failed narrowly, and the retry continues from the next untried seed on the cached datasets",
  "params": [
   "seed",
   "first",
   "last"
  ]
 },
 "type-no-cache": {
  "family": "verifier",
  "fix": "rerun with --no-cache to retrain the head from scratch",
  "params": []
 },
 "python-missing": {
  "family": "trainer-process",
  "fix": "run semantscript doctor and fix its python check: install Python 3.12 or later, or pass --python <exe> or set SEMANTSCRIPT_PYTHON",
  "params": []
 },
 "module-missing": {
  "family": "trainer-process",
  "fix": "run semantscript doctor and fix its {check} check: {python} cannot import {module}",
  "params": [
   "check",
   "python",
   "module"
  ]
 },
 "python-too-old": {
  "family": "trainer-process",
  "fix": "run semantscript doctor and fix its python check: {python} cannot parse the trainer, which needs Python 3.12 or later",
  "params": [
   "python"
  ]
 },
 "trainer-crash": {
  "family": "trainer-process",
  "fix": "run semantscript doctor to check the environment; if every check passes, rerun with --no-cache, and report a bug with the traceback if it fails again",
  "params": []
 },
 "runtime-not-loaded": {
  "family": "runtime",
  "fix": "await loadSemaArtifact() once at startup, before the first sema call (semantscript run does this for a script); if no artifact exists yet, run semantscript train",
  "params": []
 },
 "artifact-missing": {
  "family": "runtime",
  "fix": "run semantscript train to publish an artifact at {path}, or point loadSemaArtifact(), --artifact or SEMANTSCRIPT_ARTIFACT at the root train published",
  "params": [
   "path"
  ]
 },
 "artifact-path": {
  "family": "runtime",
  "fix": "point at the artifact root semantscript train published (the directory that holds current.json); never edit or symlink a release by hand",
  "params": []
 },
 "artifact-corrupt": {
  "family": "runtime",
  "fix": "switch to an intact release with semantscript releases rollback, or publish a new one with semantscript train",
  "params": []
 },
 "artifact-incompatible": {
  "family": "runtime",
  "fix": "retrain with semantscript train so the artifact matches this runtime (run semantscript build first after a compiler upgrade)",
  "params": []
 },
 "artifact-quota": {
  "family": "runtime",
  "fix": "raise the matching maximum*Bytes option of loadSemaArtifact() if the artifact is expected to be this large",
  "params": []
 },
 "artifact-resource": {
  "family": "runtime",
  "fix": "run semantscript doctor --runtime to check the native bindings, then retrain with semantscript train if they pass",
  "params": []
 },
 "unknown-function": {
  "family": "runtime",
  "fix": "the program changed after the artifact was trained: run semantscript build, then semantscript train, and reload; or load the artifact trained from this bundle",
  "params": []
 },
 "test-no-artifact": {
  "family": "cli",
  "fix": "run semantscript train to publish an artifact at {root}, or pass --artifact for one published elsewhere",
  "params": [
   "root"
  ]
 },
 "test-example-mismatch": {
  "family": "cli",
  "fix": "run semantscript build, then semantscript train, and rerun semantscript test; if it still fails, the train report's next: lines say what to change",
  "params": []
 },
 "test-function-absent": {
  "family": "cli",
  "fix": "run semantscript train on this bundle (semantscript build first if the source changed)",
  "params": []
 },
 "run-no-export": {
  "family": "cli",
  "fix": "pass --call one of the module's function exports: {exports}",
  "params": [
   "exports"
  ]
 },
 "build-no-tsconfig": {
  "family": "cli",
  "fix": "run semantscript init to set up the project, or pass --project <tsconfig.json>",
  "params": []
 },
 "build-no-outdir": {
  "family": "cli",
  "fix": "set compilerOptions.outDir in {config} (for example dist)",
  "params": [
   "config"
  ]
 }
}"""
