// Generated by scripts/generate-remedies.mjs from diagnostics/remedies.json; do not edit.
export const REMEDY_TEMPLATES = {
  "gold-rule-constraint": {
    family: "verifier",
    fix: "add the constraint always(() => {predicate}, {output}): the {count} missed examples all have {predicate} and expect {output}, and every teacher-labelled case where it holds agrees",
    params: ["predicate", "output", "count"],
  },
  "gold-repeated-miss-example": {
    family: "verifier",
    fix: "add the examples entry {example}: {count} teacher-labelled case(s) that expect {expected} are also predicted {predicted}",
    params: ["example", "count", "expected", "predicted"],
  },
  "gold-check-example": {
    family: "verifier",
    fix: "check the example {case} against the teacher's labels (it expects {expected}, the model predicts {predicted}): if it is right, add examples near it or a constraint for its rule; if not, correct it",
    params: ["case", "expected", "predicted"],
  },
  "violation-example": {
    family: "verifier",
    fix: "add the examples entry {example}: constraint {index} ({source}) is broken by {count} records",
    params: ["example", "index", "source", "count"],
  },
  "underfit-more-training": {
    family: "verifier",
    fix: "rerun with --epochs {epochs} (now {currentEpochs}) and --cases {cases} (now {currentCases}), and the default --learning-rate if you lowered it: the head gets {missed} of {total} teacher-labelled training cases wrong ({detail}), which more training fixes before any example does",
    params: [
      "epochs",
      "currentEpochs",
      "cases",
      "currentCases",
      "missed",
      "total",
      "detail",
    ],
  },
  "violation-denser-data": {
    family: "verifier",
    fix: "sample the boundaries more densely: rerun with --cases {cases} (now {current}), or accept isolated misses by recording a tolerance with --max-constraint-violation-rate",
    params: ["cases", "current"],
  },
  "calibration-more-cases": {
    family: "verifier",
    fix: "rerun with --cases {cases} (now {current}): ECE {ece} is measured on {rows} calibration rows, and more cases give more of them",
    params: ["cases", "current", "ece", "rows"],
  },
  "calibration-more-epochs": {
    family: "verifier",
    fix: "rerun with --epochs {epochs} (now {current}): accuracy {accuracy} shows an underfit head, which calibrates poorly",
    params: ["epochs", "current", "accuracy"],
  },
  "seed-retry-attempts": {
    family: "verifier",
    fix: "rerun with --seed-attempts {attempts}: the failure was narrow, and the retry trains the next seeds on the cached datasets without a teacher request",
    params: ["attempts"],
  },
  "seed-retry-next-seed": {
    family: "verifier",
    fix: "rerun with --seed {seed}: seeds {first} to {last} failed narrowly, and the retry continues from the next untried seed on the cached datasets",
    params: ["seed", "first", "last"],
  },
  "type-no-cache": {
    family: "verifier",
    fix: "rerun with --no-cache to retrain the head from scratch",
    params: [],
  },
  "python-missing": {
    family: "trainer-process",
    fix: "run {doctor} and fix its python check: install Python 3.12 or later, or point the CLI at one with --python <exe> or SEMANTSCRIPT_PYTHON",
    params: ["doctor"],
  },
  "module-missing": {
    family: "trainer-process",
    fix: "run {doctor} and fix its {check} check: {python} cannot import {module}",
    params: ["doctor", "check", "python", "module"],
  },
  "python-too-old": {
    family: "trainer-process",
    fix: "run {doctor} and fix its python check: {python} cannot parse the trainer, which needs Python 3.12 or later",
    params: ["doctor", "python"],
  },
  "trainer-crash": {
    family: "trainer-process",
    fix: "run {doctor} to check the environment; if every check passes, rerun with --no-cache, and report a bug with the traceback if it fails again",
    params: ["doctor"],
  },
  "training-extra-missing": {
    family: "trainer-process",
    fix: "run {doctor} and fix its {check} check: {python} cannot import {module}",
    params: ["doctor", "check", "python", "module"],
  },
  "bundle-unreadable": {
    family: "trainer-process",
    fix: "run semantscript build to write the IR bundle, or pass --bundle the build's semantscript.ir.v1.json (now {bundle})",
    params: ["bundle"],
  },
  "bundle-invalid": {
    family: "trainer-process",
    fix: "run semantscript build and pass its semantscript.ir.v1.json as --bundle (now {bundle}); never edit the bundle by hand",
    params: ["bundle"],
  },
  "teacher-config-invalid": {
    family: "trainer-process",
    fix: "run {doctor} and fix its teacher-config check: {teacher} is not a valid teacher file (docs/teachers.md lists every key)",
    params: ["doctor", "teacher"],
  },
  "teacher-transport": {
    family: "trainer-process",
    fix: "run {doctor} --probe request to test the teacher, then rerun semantscript train: the datasets that finished stay cached",
    params: ["doctor"],
  },
  "trainer-killed": {
    family: "trainer-process",
    fix: "run {doctor} and fix its torch and device checks, then rerun with a smaller --batch-size or with --device cpu: the datasets that finished stay cached, so the rerun asks the teacher only for the rest",
    params: ["doctor"],
  },
  "train-out-of-memory": {
    family: "trainer-process",
    fix: "rerun with a smaller --batch-size or with --device cpu: the datasets that finished stay cached",
    params: [],
  },
  "encoder-download-failed": {
    family: "trainer-process",
    fix: "check that this machine can reach https://huggingface.co (or the HF_ENDPOINT mirror, through HTTPS_PROXY if one is needed), unset HF_HUB_OFFLINE and TRANSFORMERS_OFFLINE, or copy a Hugging Face cache that holds the encoder into HF_HOME; if you passed --encoder-name or --encoder-revision, check that the model and revision exist; then rerun semantscript train",
    params: [],
  },
  "train-path-unwritable": {
    family: "trainer-process",
    fix: "check that {path} can be written (a directory, with write permission and free space), or pass --cache-dir or --artifact another path, then rerun semantscript train",
    params: ["path"],
  },
  "artifact-export-failed": {
    family: "trainer-process",
    fix: "run {doctor} and fix its onnxruntime check; if every check passes, rerun with --no-cache, and report a bug with this message if the export fails again",
    params: ["doctor"],
  },
  "train-option-invalid": {
    family: "trainer-process",
    fix: "correct the option the message names and rerun semantscript train (docs/cli-reference.md lists each option and its range)",
    params: [],
  },
  "teacher-rejected": {
    family: "trainer-process",
    fix: "rerun semantscript train: rejected answers are not replayed, so the teacher is asked again; if it fails the same way, use a stronger teacher model or a lower --counterfactual-ratio (0.5), and check that a single-field edit can cross the predicate of the constraint the message names",
    params: [],
  },
  "train-failed": {
    family: "trainer-process",
    fix: "if the message names a setting or a file, correct it and rerun semantscript train; otherwise run {doctor} to check the environment, and report a bug with this message if every check passes",
    params: ["doctor"],
  },
  "train-no-gold-examples": {
    family: "teacher",
    fix: "add an examples: [{ inputs, output }] entry to the sema call, then run semantscript build and semantscript train",
    params: [],
  },
  "train-gold-example-invalid": {
    family: "teacher",
    fix: "correct the example or the constraint it breaks in the sema call, then run semantscript build and semantscript train",
    params: [],
  },
  "constraint-constant": {
    family: "teacher",
    fix: "rewrite the predicate of that constraint over the inputs so that it holds for some inputs and not for others, then run semantscript build and semantscript train",
    params: [],
  },
  "teacher-constraints-undecided": {
    family: "teacher",
    fix: 'add always/never constraints until exactly one output is admissible for every input, or label the inputs they leave open with a language-model teacher: write a teacher TOML with [teacher] backend = "constraints" and a [teacher.fallback] table (backend = "anthropic" or "ollama" and its model), and pass it with --teacher <file> (docs/teachers.md)',
    params: [],
  },
  "teacher-constraints-contradict": {
    family: "teacher",
    fix: "correct the predicates or outputs of the constraints active on that input so that exactly one output is admissible, then run semantscript build and semantscript train",
    params: [],
  },
  "teacher-constraints-none": {
    family: "teacher",
    fix: 'add always/never constraints that decide every input, or let a language-model teacher label it: write a teacher TOML with [teacher] backend = "constraints" and a [teacher.fallback] table (backend = "anthropic" or "ollama" and its model), and pass it with --teacher <file> (docs/teachers.md)',
    params: [],
  },
  "teacher-constraints-object": {
    family: "teacher",
    fix: 'let a language-model teacher label it: write a teacher TOML with [teacher] backend = "constraints" and a [teacher.fallback] table (backend = "anthropic" or "ollama" and its model), and pass it with --teacher <file> (docs/teachers.md)',
    params: [],
  },
  "teacher-constraints-sampling": {
    family: "teacher",
    fix: 'write a teacher TOML with [teacher] backend = "constraints" and a [teacher.ranges] table that widens the sampling ranges, pass it with --teacher <file> (docs/teachers.md), or request fewer --cases',
    params: [],
  },
  "teacher-constraints-twins": {
    family: "teacher",
    fix: 'write a teacher TOML with [teacher] backend = "constraints" and a [teacher.ranges] table that widens the sampling ranges, or twin_filter = false when the constraints always give one output, and pass it with --teacher <file> (docs/teachers.md)',
    params: [],
  },
  "training-single-group": {
    family: "teacher",
    fix: "lower --counterfactual-ratio (0.5, or 0 when the inputs are a few booleans or enum values), request fewer --cases, or, with the constraints teacher, widen the number ranges in [teacher.ranges] (docs/teachers.md)",
    params: [],
  },
  "teacher-few-distinct": {
    family: "teacher",
    fix: "widen the input space the teacher samples (a [teacher.ranges] table for the constraints teacher, docs/teachers.md), or request fewer --cases",
    params: [],
  },
  "teacher-spend-cap": {
    family: "teacher",
    fix: "rerun with a higher --max-cost-usd, or without it, to resume: every dataset finished before the stop stays cached in {cache}",
    params: ["cache"],
  },
  "teacher-spend-cap-journal": {
    family: "teacher",
    fix: "rerun with a higher --max-cost-usd, or without it, to resume: every dataset finished before the stop stays cached in {cache}, and the {count} paid teacher response(s) kept in {journal} replay at no cost",
    params: ["cache", "count", "journal"],
  },
  "teacher-price-unknown": {
    family: "teacher",
    fix: "check the teacher model name, or add a [teacher.pricing] table with input_usd_per_million and output_usd_per_million to the teacher file (docs/teachers.md)",
    params: [],
  },
  "runtime-not-loaded": {
    family: "runtime",
    fix: "await loadSemaArtifact() once at startup, before the first sema call (semantscript run does this for a script); if no artifact exists yet, run semantscript train",
    params: [],
  },
  "artifact-missing": {
    family: "runtime",
    fix: "run semantscript train to publish an artifact at {path}, or point loadSemaArtifact(), --artifact or SEMANTSCRIPT_ARTIFACT at the root train published",
    params: ["path"],
  },
  "artifact-path": {
    family: "runtime",
    fix: "point at the artifact root semantscript train published (the directory that holds current.json); never edit or symlink a release by hand",
    params: [],
  },
  "artifact-corrupt": {
    family: "runtime",
    fix: "run semantscript releases list to find an intact release, then switch to it with semantscript releases rollback <release>, which also rewrites a broken current.json (pass --artifact <root> to both when the artifact is not .semantscript/artifact); or publish a new one with semantscript train",
    params: [],
  },
  "artifact-incompatible": {
    family: "runtime",
    fix: "retrain with semantscript train so the artifact matches this runtime (run semantscript build first after a compiler upgrade)",
    params: [],
  },
  "artifact-quota": {
    family: "runtime",
    fix: "raise the matching maximum*Bytes option of loadSemaArtifact() if the artifact is expected to be this large",
    params: [],
  },
  "artifact-resource": {
    family: "runtime",
    fix: "run semantscript doctor --runtime to check the native bindings, then retrain with semantscript train if they pass",
    params: [],
  },
  "unknown-function": {
    family: "runtime",
    fix: "the program changed after the artifact was trained: run semantscript build, then semantscript train, and reload; or load the artifact trained from this bundle",
    params: [],
  },
  "test-no-artifact": {
    family: "cli",
    fix: "run semantscript train to publish an artifact at {root}, or pass --artifact for one published elsewhere",
    params: ["root"],
  },
  "test-example-mismatch": {
    family: "cli",
    fix: "run semantscript build, then semantscript train, and rerun semantscript test; if it still fails, the train report's next: lines say what to change",
    params: [],
  },
  "test-function-absent": {
    family: "cli",
    fix: "run semantscript train on this bundle (semantscript build first if the source changed)",
    params: [],
  },
  "test-function-unverified": {
    family: "cli",
    fix: "retrain with semantscript train, following the next: lines of its report, or switch to a passing release with semantscript releases rollback <release> (semantscript releases list shows which releases pass)",
    params: [],
  },
  "test-artifact-unreadable": {
    family: "cli",
    fix: "run semantscript releases list to find an intact release, then switch to it with semantscript releases rollback <release>, which also rewrites a broken current.json (pass --artifact <root> to both when the artifact is not .semantscript/artifact); or publish a new one with semantscript train",
    params: [],
  },
  "run-no-export": {
    family: "cli",
    fix: "pass --call one of the module's function exports: {exports}",
    params: ["exports"],
  },
  "build-no-tsconfig": {
    family: "cli",
    fix: "create {config} with npx -p typescript tsc --init --rootDir . --outDir dist, then run semantscript init to add the SemantScript plugins, or pass --project <tsconfig.json>",
    params: ["config"],
  },
  "build-tsconfig-invalid": {
    family: "cli",
    fix: "correct {config} as the errors above say (it must be one JSON object whose include or files select the .sem.ts sources), then rerun semantscript build",
    params: ["config"],
  },
  "build-no-outdir": {
    family: "cli",
    fix: "set compilerOptions.outDir in {config} (for example dist)",
    params: ["config"],
  },
  "train-no-teacher": {
    family: "cli",
    fix: "run semantscript init --teacher anthropic, openrouter, ollama or constraints to write a teacher file, set ANTHROPIC_API_KEY to use the default Anthropic teacher, or pass --teacher constraints when the constraints decide every input",
    params: [],
  },
  "teacher-probe-none": {
    family: "cli",
    fix: "run semantscript init --teacher anthropic, openrouter, ollama or constraints to write .semantscript/teacher.toml, or pass --teacher <teacher.toml>",
    params: [],
  },
  "doctor-node": {
    family: "doctor",
    fix: "install Node {minimum} or later (the repository's .nvmrc pins the tested release; nvm install)",
    params: ["minimum"],
  },
  "doctor-runtime-unresolved": {
    family: "doctor",
    fix: "npm install in the project (the CLI loads the runtime from @semantscript/core)",
    params: [],
  },
  "doctor-runtime-native": {
    family: "doctor",
    fix: "run npm install (or npm rebuild {packages}) on this machine; the native binaries are per platform, so a node_modules copied from another OS or architecture does not load",
    params: ["packages"],
  },
  "doctor-python": {
    family: "doctor",
    fix: "install Python 3.12 or later, or point the CLI at one with --python <exe> or SEMANTSCRIPT_PYTHON",
    params: [],
  },
  "doctor-trainer-import": {
    family: "doctor",
    fix: 'install the trainer into {python}: pip install "semantscript-trainer[training]" (in a SemantScript checkout: pip install -e ".[training]", or run the CLI from the checkout, which adds trainer/src and model/src to PYTHONPATH)',
    params: ["python"],
  },
  "doctor-trainer-outdated": {
    family: "doctor",
    fix: "update the SemantScript trainer to the release that matches this CLI, or pass --no-preflight to train without the checks",
    params: [],
  },
  "doctor-trainer-error": {
    family: "doctor",
    fix: "run {python} -m {module} doctor to see the full error",
    params: ["python", "module"],
  },
  "doctor-trainer-clients": {
    family: "doctor",
    fix: "pip install semantscript-trainer (installs the teacher clients anthropic and openai; in a SemantScript checkout: pip install -e .)",
    params: [],
  },
  "doctor-model": {
    family: "doctor",
    fix: "pip install semantscript-trainer (in a SemantScript checkout: pip install -e ., or run the CLI from the checkout so model/src is on PYTHONPATH)",
    params: [],
  },
  "doctor-training-extra": {
    family: "doctor",
    fix: 'install the training extra into this interpreter: pip install "semantscript-trainer[training]" (in a SemantScript checkout: pip install -e ".[training]"; for a GPU, install the CUDA or ROCm torch build from https://pytorch.org/get-started/locally/ first)',
    params: [],
  },
  "doctor-reinstall": {
    family: "doctor",
    fix: "reinstall {name} into this interpreter (pip install --force-reinstall {name})",
    params: ["name"],
  },
  "doctor-platform-env-import": {
    family: "doctor",
    fix: "{command} (see platform-env)",
    params: ["command"],
  },
  "doctor-platform-env": {
    family: "doctor",
    fix: "{command}; {persist}",
    params: ["command", "persist"],
  },
  "doctor-device-invalid": {
    family: "doctor",
    fix: "pass --device auto, cpu or cuda (ROCm GPUs are cuda to PyTorch)",
    params: [],
  },
  "doctor-device-query": {
    family: "doctor",
    fix: "check the GPU driver (nvidia-smi or rocminfo), or pass --device cpu",
    params: [],
  },
  "doctor-device-missing": {
    family: "doctor",
    fix: "install the torch build for this GPU (https://pytorch.org/get-started/locally/), or drop --device cuda to train on the CPU",
    params: [],
  },
  "doctor-device-mps": {
    family: "doctor",
    fix: "expect slower runs; lower --cases or --epochs for a first try",
    params: [],
  },
  "doctor-device-cpu": {
    family: "doctor",
    fix: "if this machine has an NVIDIA or AMD GPU, install the matching torch build (https://pytorch.org/get-started/locally/); otherwise lower --cases or --epochs",
    params: [],
  },
  "doctor-teacher-file-missing": {
    family: "doctor",
    fix: "write a [teacher] TOML there (docs/teachers.md), pass --teacher <file>, or pass --teacher constraints (lower case) to label with the expressions' own constraints",
    params: [],
  },
  "doctor-teacher-file-invalid": {
    family: "doctor",
    fix: "fix the [teacher] table (docs/teachers.md lists every key)",
    params: [],
  },
  "doctor-teacher-none": {
    family: "doctor",
    fix: "write a [teacher] TOML (docs/teachers.md; Ollama needs no key), set ANTHROPIC_API_KEY to use the default Anthropic teacher, or pass --teacher constraints when the constraints decide every input",
    params: [],
  },
  "doctor-teacher-key-openrouter": {
    family: "doctor",
    fix: "{command} for this shell (base_url points at OpenRouter, which accepts its own key on the Anthropic route)",
    params: ["command"],
  },
  "doctor-teacher-key": {
    family: "doctor",
    fix: "{command} (an OpenRouter key when base_url is OpenRouter), or switch to the ollama backend (docs/teachers.md)",
    params: ["command"],
  },
  "doctor-teacher-pull": {
    family: "doctor",
    fix: "ollama pull {model}",
    params: ["model"],
  },
  "doctor-teacher-refused": {
    family: "doctor",
    fix: "the key was refused: check ANTHROPIC_API_KEY (an OpenRouter key when base_url is OpenRouter)",
    params: [],
  },
  "doctor-teacher-model-name": {
    family: "doctor",
    fix: "check the model name {model} in the teacher file",
    params: ["model"],
  },
  "doctor-teacher-ollama-down": {
    family: "doctor",
    fix: "start the server (ollama serve) or fix base_url in the teacher file",
    params: [],
  },
  "doctor-teacher-network": {
    family: "doctor",
    fix: "check the network and base_url in the teacher file",
    params: [],
  },
  "doctor-teacher-other": {
    family: "doctor",
    fix: "see docs/teachers.md",
    params: [],
  },
  "doctor-venv": {
    family: "doctor",
    fix: "if the packages are in {venv} rather than {python} (the default interpreter), pass --python {venv} or set the SEMANTSCRIPT_PYTHON environment variable to {venv}",
    params: ["venv", "python"],
  },
  "editor-no-artifact": {
    family: "editor",
    fix: "run semantscript train (or semantscript dev) to publish an artifact at {root}",
    params: ["root"],
  },
  "editor-unreadable": {
    family: "editor",
    fix: "run semantscript releases list to find an intact release, then switch to it with semantscript releases rollback <release>, which also rewrites a broken current.json (pass --artifact <root> to both when the artifact is not .semantscript/artifact); or publish a new one with semantscript train",
    params: [],
  },
  "editor-not-in-artifact": {
    family: "editor",
    fix: "run semantscript train; the build cache retrains only the expressions that changed",
    params: [],
  },
  "editor-no-examples": {
    family: "editor",
    fix: "add a few examples: [{ inputs, output }] entries to this sema call, the first thing to try",
    params: [],
  },
  "editor-accuracy": {
    family: "editor",
    fix: "add examples for the cases it misses, or a constraint for the rule it breaks, then retrain (the train report's next: lines name them)",
    params: [],
  },
  "editor-ece": {
    family: "editor",
    fix: "train with more cases (--cases), or set a confidence threshold with a fallback so low-confidence answers are caught",
    params: [],
  },
  "int8-gate-refused": {
    family: "cli",
    fix: "keep serving the current release (current.json is unchanged){alternative}; to publish anyway, record a tolerance that admits these figures with {command} {tolerance}, which the manifest keeps and semantscript releases show prints",
    params: ["alternative", "command", "tolerance"],
  },
  "int8-records-missing": {
    family: "cli",
    fix: "pass --cache-dir the build cache the release was trained with (it needs dataset {dataset} for {function}, not found under {cache}); when that cache is gone, retrain with semantscript train so the new release's records are cached, then derive from it",
    params: ["dataset", "function", "cache"],
  },
} as const;

/** Every remedy a tool prints, keyed by its id in `diagnostics/remedies.json`. */
export type RemedyId = keyof typeof REMEDY_TEMPLATES;

/** The placeholders one remedy's fix template names. */
export type RemedyParams<Id extends RemedyId> = Readonly<
  Record<(typeof REMEDY_TEMPLATES)[Id]["params"][number], string | number>
>;

/** The family a remedy belongs to (verifier, trainer-process, runtime, cli, doctor or editor). */
export function remedyFamily(id: RemedyId): string {
  return template(id).family;
}

/**
 * The fix text a tool prints for a failure: the template from
 * `diagnostics/remedies.json` with every `{name}` replaced by `params[name]`.
 * An unknown id, a missing parameter or one the template does not name is a
 * programming error and throws.
 */
export function remedy<Id extends RemedyId>(
  id: Id,
  ...args: (typeof REMEDY_TEMPLATES)[Id]["params"] extends readonly []
    ? []
    : [params: RemedyParams<Id>]
): string {
  const entry = template(id);
  const params: Readonly<Record<string, string | number>> = args[0] ?? {};
  const names: readonly string[] = entry.params;
  for (const key of Object.keys(params)) {
    if (!names.includes(key)) {
      throw new TypeError(`remedy ${id} has no parameter ${key}`);
    }
  }
  return entry.fix.replace(/\{([a-z][a-zA-Z0-9]*)\}/gu, (_match, name) => {
    const value = params[name as string];
    if (value === undefined) {
      throw new TypeError(`remedy ${id} needs parameter ${String(name)}`);
    }
    return String(value);
  });
}

function template(id: string): {
  readonly family: string;
  readonly fix: string;
  readonly params: readonly string[];
} {
  if (!Object.hasOwn(REMEDY_TEMPLATES, id)) {
    throw new TypeError(`unknown remedy ${JSON.stringify(id)}`);
  }
  return REMEDY_TEMPLATES[id as RemedyId];
}
