// Generated by scripts/generate-remedies.mjs from diagnostics/remedies.json; do not edit.
export const REMEDY_TEMPLATES = {
  "gold-rule-constraint": {
    family: "verifier",
    fix: "add the constraint always(() => {predicate}, {output}): the {count} missed examples all have {predicate} and expect {output}, and every teacher-labelled case where it holds agrees",
    params: ["predicate", "output", "count"],
  },
  "gold-repeated-miss-example": {
    family: "verifier",
    fix: "add the examples entry {example}: {count} teacher-labelled case(s) that expect {expected} are also predicted {predicted}",
    params: ["example", "count", "expected", "predicted"],
  },
  "gold-check-example": {
    family: "verifier",
    fix: "check the example {case} against the teacher's labels (it expects {expected}, the model predicts {predicted}): if it is right, add examples near it or a constraint for its rule; if not, correct it",
    params: ["case", "expected", "predicted"],
  },
  "violation-example": {
    family: "verifier",
    fix: "add the examples entry {example}: constraint {index} ({source}) is broken by {count} records",
    params: ["example", "index", "source", "count"],
  },
  "violation-denser-data": {
    family: "verifier",
    fix: "sample the boundaries more densely: rerun with --cases {cases} (now {current}) or a higher --counterfactual-ratio, or record a tolerance with --max-constraint-violation-rate (decision-8)",
    params: ["cases", "current"],
  },
  "calibration-more-cases": {
    family: "verifier",
    fix: "rerun with --cases {cases} (now {current}): ECE {ece} is measured on {rows} calibration rows, and more cases give more of them",
    params: ["cases", "current", "ece", "rows"],
  },
  "calibration-more-epochs": {
    family: "verifier",
    fix: "rerun with --epochs {epochs} (now {current}): accuracy {accuracy} shows an underfit head, which calibrates poorly",
    params: ["epochs", "current", "accuracy"],
  },
  "seed-retry-attempts": {
    family: "verifier",
    fix: "rerun with --seed-attempts {attempts}: the failure was narrow, and the retry trains the next seeds on the cached datasets without a teacher request",
    params: ["attempts"],
  },
  "seed-retry-next-seed": {
    family: "verifier",
    fix: "rerun with --seed {seed}: seeds {first} to {last} failed narrowly, and the retry continues from the next untried seed on the cached datasets",
    params: ["seed", "first", "last"],
  },
  "type-no-cache": {
    family: "verifier",
    fix: "rerun with --no-cache to retrain the head from scratch",
    params: [],
  },
  "python-missing": {
    family: "trainer-process",
    fix: "run semantscript doctor and fix its python check: install Python 3.12 or later, or point the CLI at one with --python <exe> or SEMANTSCRIPT_PYTHON",
    params: [],
  },
  "module-missing": {
    family: "trainer-process",
    fix: "run {doctor} and fix its {check} check: {python} cannot import {module}",
    params: ["doctor", "check", "python", "module"],
  },
  "python-too-old": {
    family: "trainer-process",
    fix: "run {doctor} and fix its python check: {python} cannot parse the trainer, which needs Python 3.12 or later",
    params: ["doctor", "python"],
  },
  "trainer-crash": {
    family: "trainer-process",
    fix: "run {doctor} to check the environment; if every check passes, rerun with --no-cache, and report a bug with the traceback if it fails again",
    params: ["doctor"],
  },
  "training-extra-missing": {
    family: "trainer-process",
    fix: "run {doctor} and fix its {check} check: {python} cannot import {module}",
    params: ["doctor", "check", "python", "module"],
  },
  "bundle-unreadable": {
    family: "trainer-process",
    fix: "run semantscript build to write the IR bundle, or pass --bundle the build's semantscript.ir.v1.json (now {bundle})",
    params: ["bundle"],
  },
  "bundle-invalid": {
    family: "trainer-process",
    fix: "run semantscript build and pass its semantscript.ir.v1.json as --bundle (now {bundle}); never edit the bundle by hand",
    params: ["bundle"],
  },
  "teacher-config-invalid": {
    family: "trainer-process",
    fix: "run {doctor} and fix its teacher-config check: {teacher} is not a valid teacher file (docs/teachers.md lists every key)",
    params: ["doctor", "teacher"],
  },
  "teacher-transport": {
    family: "trainer-process",
    fix: "run {doctor} --probe request to test the teacher, then rerun semantscript train: the datasets that finished stay cached",
    params: ["doctor"],
  },
  "runtime-not-loaded": {
    family: "runtime",
    fix: "await loadSemaArtifact() once at startup, before the first sema call (semantscript run does this for a script); if no artifact exists yet, run semantscript train",
    params: [],
  },
  "artifact-missing": {
    family: "runtime",
    fix: "run semantscript train to publish an artifact at {path}, or point loadSemaArtifact(), --artifact or SEMANTSCRIPT_ARTIFACT at the root train published",
    params: ["path"],
  },
  "artifact-path": {
    family: "runtime",
    fix: "point at the artifact root semantscript train published (the directory that holds current.json); never edit or symlink a release by hand",
    params: [],
  },
  "artifact-corrupt": {
    family: "runtime",
    fix: "switch to an intact release with semantscript releases rollback, or publish a new one with semantscript train",
    params: [],
  },
  "artifact-incompatible": {
    family: "runtime",
    fix: "retrain with semantscript train so the artifact matches this runtime (run semantscript build first after a compiler upgrade)",
    params: [],
  },
  "artifact-quota": {
    family: "runtime",
    fix: "raise the matching maximum*Bytes option of loadSemaArtifact() if the artifact is expected to be this large",
    params: [],
  },
  "artifact-resource": {
    family: "runtime",
    fix: "run semantscript doctor --runtime to check the native bindings, then retrain with semantscript train if they pass",
    params: [],
  },
  "unknown-function": {
    family: "runtime",
    fix: "the program changed after the artifact was trained: run semantscript build, then semantscript train, and reload; or load the artifact trained from this bundle",
    params: [],
  },
  "test-no-artifact": {
    family: "cli",
    fix: "run semantscript train to publish an artifact at {root}, or pass --artifact for one published elsewhere",
    params: ["root"],
  },
  "test-example-mismatch": {
    family: "cli",
    fix: "run semantscript build, then semantscript train, and rerun semantscript test; if it still fails, the train report's next: lines say what to change",
    params: [],
  },
  "test-function-absent": {
    family: "cli",
    fix: "run semantscript train on this bundle (semantscript build first if the source changed)",
    params: [],
  },
  "test-function-unverified": {
    family: "cli",
    fix: "retrain with semantscript train, following the next: lines of its report, or switch to a passing release with semantscript releases rollback",
    params: [],
  },
  "test-artifact-unreadable": {
    family: "cli",
    fix: "switch to an intact release with semantscript releases rollback, or publish a new one with semantscript train",
    params: [],
  },
  "run-no-export": {
    family: "cli",
    fix: "pass --call one of the module's function exports: {exports}",
    params: ["exports"],
  },
  "build-no-tsconfig": {
    family: "cli",
    fix: "run semantscript init to set up the project, or pass --project <tsconfig.json>",
    params: [],
  },
  "build-no-outdir": {
    family: "cli",
    fix: "set compilerOptions.outDir in {config} (for example dist)",
    params: ["config"],
  },
  "doctor-node": {
    family: "doctor",
    fix: "install Node {minimum} or later (the repository's .nvmrc pins the tested release; nvm install)",
    params: ["minimum"],
  },
  "doctor-runtime-unresolved": {
    family: "doctor",
    fix: "npm install in the project (the CLI loads the runtime from @semantscript/core)",
    params: [],
  },
  "doctor-runtime-native": {
    family: "doctor",
    fix: "run npm install (or npm rebuild {packages}) on this machine; the native binaries are per platform, so a node_modules copied from another OS or architecture does not load",
    params: ["packages"],
  },
  "doctor-python": {
    family: "doctor",
    fix: "install Python 3.12 or later, or point the CLI at one with --python <exe> or SEMANTSCRIPT_PYTHON",
    params: [],
  },
  "doctor-trainer-import": {
    family: "doctor",
    fix: 'pip install -e ".[training]" from the SemantScript checkout into {python}, or run the CLI from the checkout (it adds trainer/src and model/src to PYTHONPATH)',
    params: ["python"],
  },
  "doctor-trainer-outdated": {
    family: "doctor",
    fix: "update the SemantScript trainer to the release that matches this CLI, or pass --no-preflight to train without the checks",
    params: [],
  },
  "doctor-trainer-error": {
    family: "doctor",
    fix: "run {python} -m {module} doctor to see the full error",
    params: ["python", "module"],
  },
  "doctor-trainer-clients": {
    family: "doctor",
    fix: "pip install -e . from the SemantScript checkout (installs the teacher clients anthropic and openai)",
    params: [],
  },
  "doctor-model": {
    family: "doctor",
    fix: "pip install -e . from the SemantScript checkout, or run the CLI from the checkout so model/src is on PYTHONPATH",
    params: [],
  },
  "doctor-training-extra": {
    family: "doctor",
    fix: 'install the training extra into this interpreter: pip install -e ".[training]" from the SemantScript checkout (for a GPU, install the CUDA or ROCm torch build from https://pytorch.org/get-started/locally/ first)',
    params: [],
  },
  "doctor-reinstall": {
    family: "doctor",
    fix: "reinstall {name} into this interpreter (pip install --force-reinstall {name})",
    params: ["name"],
  },
  "doctor-platform-env-import": {
    family: "doctor",
    fix: "{command} (see platform-env)",
    params: ["command"],
  },
  "doctor-platform-env": {
    family: "doctor",
    fix: "{command}; {persist}",
    params: ["command", "persist"],
  },
  "doctor-device-invalid": {
    family: "doctor",
    fix: "pass --device auto, cpu or cuda (ROCm GPUs are cuda to PyTorch)",
    params: [],
  },
  "doctor-device-query": {
    family: "doctor",
    fix: "check the GPU driver (nvidia-smi or rocminfo), or pass --device cpu",
    params: [],
  },
  "doctor-device-missing": {
    family: "doctor",
    fix: "install the torch build for this GPU (https://pytorch.org/get-started/locally/), or drop --device cuda to train on the CPU",
    params: [],
  },
  "doctor-device-mps": {
    family: "doctor",
    fix: "expect slower runs; lower --cases or --epochs for a first try",
    params: [],
  },
  "doctor-device-cpu": {
    family: "doctor",
    fix: "if this machine has an NVIDIA or AMD GPU, install the matching torch build (https://pytorch.org/get-started/locally/); otherwise lower --cases or --epochs",
    params: [],
  },
  "doctor-teacher-file-missing": {
    family: "doctor",
    fix: "write a [teacher] TOML there (docs/teachers.md), pass --teacher <file>, or pass --teacher constraints (lower case) to label with the expressions' own constraints",
    params: [],
  },
  "doctor-teacher-file-invalid": {
    family: "doctor",
    fix: "fix the [teacher] table (docs/teachers.md lists every key)",
    params: [],
  },
  "doctor-teacher-none": {
    family: "doctor",
    fix: "write a [teacher] TOML (docs/teachers.md; Ollama needs no key), set ANTHROPIC_API_KEY to use the default Anthropic teacher, or pass --teacher constraints when the constraints decide every input",
    params: [],
  },
  "doctor-teacher-key-openrouter": {
    family: "doctor",
    fix: "{command} for this shell (base_url points at OpenRouter, which accepts its own key on the Anthropic route)",
    params: ["command"],
  },
  "doctor-teacher-key": {
    family: "doctor",
    fix: "{command} (an OpenRouter key when base_url is OpenRouter), or switch to the ollama backend (docs/teachers.md)",
    params: ["command"],
  },
  "doctor-teacher-pull": {
    family: "doctor",
    fix: "ollama pull {model}",
    params: ["model"],
  },
  "doctor-teacher-refused": {
    family: "doctor",
    fix: "the key was refused: check ANTHROPIC_API_KEY (an OpenRouter key when base_url is OpenRouter)",
    params: [],
  },
  "doctor-teacher-model-name": {
    family: "doctor",
    fix: "check the model name {model} in the teacher file",
    params: ["model"],
  },
  "doctor-teacher-ollama-down": {
    family: "doctor",
    fix: "start the server (ollama serve) or fix base_url in the teacher file",
    params: [],
  },
  "doctor-teacher-network": {
    family: "doctor",
    fix: "check the network and base_url in the teacher file",
    params: [],
  },
  "doctor-teacher-other": {
    family: "doctor",
    fix: "see docs/teachers.md",
    params: [],
  },
  "doctor-venv": {
    family: "doctor",
    fix: "if the packages are in {venv} rather than {python} (the default interpreter), pass --python {venv} or set the SEMANTSCRIPT_PYTHON environment variable to {venv}",
    params: ["venv", "python"],
  },
  "editor-no-artifact": {
    family: "editor",
    fix: "run semantscript train (or semantscript dev) to publish an artifact at {root}",
    params: ["root"],
  },
  "editor-unreadable": {
    family: "editor",
    fix: "switch to an intact release with semantscript releases rollback, or publish a new one with semantscript train",
    params: [],
  },
  "editor-not-in-artifact": {
    family: "editor",
    fix: "run semantscript train; the build cache retrains only the expressions that changed",
    params: [],
  },
  "editor-no-examples": {
    family: "editor",
    fix: "add a few examples: [{ inputs, output }] entries to this sema call, the first thing to try",
    params: [],
  },
  "editor-accuracy": {
    family: "editor",
    fix: "add examples for the cases it misses, or a constraint for the rule it breaks, then retrain (the train report's next: lines name them)",
    params: [],
  },
  "editor-ece": {
    family: "editor",
    fix: "train with more cases (--cases), or set a confidence threshold with a fallback so low-confidence answers are caught",
    params: [],
  },
} as const;

/** Every remedy a tool prints, keyed by its id in `diagnostics/remedies.json`. */
export type RemedyId = keyof typeof REMEDY_TEMPLATES;

/** The placeholders one remedy's fix template names. */
export type RemedyParams<Id extends RemedyId> = Readonly<
  Record<(typeof REMEDY_TEMPLATES)[Id]["params"][number], string | number>
>;

/** The family a remedy belongs to (verifier, trainer-process, runtime, cli, doctor or editor). */
export function remedyFamily(id: RemedyId): string {
  return template(id).family;
}

/**
 * The fix text a tool prints for a failure: the template from
 * `diagnostics/remedies.json` with every `{name}` replaced by `params[name]`.
 * An unknown id, a missing parameter or one the template does not name is a
 * programming error and throws.
 */
export function remedy<Id extends RemedyId>(
  id: Id,
  ...args: (typeof REMEDY_TEMPLATES)[Id]["params"] extends readonly []
    ? []
    : [params: RemedyParams<Id>]
): string {
  const entry = template(id);
  const params: Readonly<Record<string, string | number>> = args[0] ?? {};
  const names: readonly string[] = entry.params;
  for (const key of Object.keys(params)) {
    if (!names.includes(key)) {
      throw new TypeError(`remedy ${id} has no parameter ${key}`);
    }
  }
  return entry.fix.replace(/\{([a-z][a-zA-Z0-9]*)\}/gu, (_match, name) => {
    const value = params[name as string];
    if (value === undefined) {
      throw new TypeError(`remedy ${id} needs parameter ${String(name)}`);
    }
    return String(value);
  });
}

function template(id: string): {
  readonly family: string;
  readonly fix: string;
  readonly params: readonly string[];
} {
  if (!Object.hasOwn(REMEDY_TEMPLATES, id)) {
    throw new TypeError(`unknown remedy ${JSON.stringify(id)}`);
  }
  return REMEDY_TEMPLATES[id as RemedyId];
}
